data:
  database_path: datasets/BBDD/
  query_path: datasets/qsd1_w1/

retrieval:
  color_space: [lab]
  bins: [128, 64, 32, 16, 8]
  distances: [l1, x2, euclidean, hist_intersection, hellinger, canberra]
  preprocessings: [clahe]
  hier_levels: [1, 2, 3, 4]
  hist_dims: [1, 2, 3]
  k: [1, 5]

evaluation:
  val: true