data:
  database_path: datasets/BBDD/
  query_path: datasets/qsd1_w1/

retrieval:
  color_space_list: [lab]
  preprocesses_list: [clahe]

  bins_list: [100]
  hierarchy_list: [1, 2, 3, 4, 5, 6]
  hist_dims_list: [1]

  distances_list: [l1, euclidean, hist_intersection]

  k_list: [1, 5]

evaluation:
  val: true