data:
  database_path: ../BBDD/
  query_path: ../qst1_w1/

retrieval:
  color_space: [lab]
  bins: [100]
  distances: [canberra]
  preprocessings: [clahe]
  k: [10]

evaluation:
  val: false

output:
  pickle_filename: 'result.pkl'