data:
  database_path: datasets/BBDD/
  query_path: datasets/qst1_w2/

retrieval:
  color_space_list: [lab]
  preprocesses_list: [clahe]

  bins_list: [100]
  blocks_list: [16]
  hist_dims_list: [1]

  distances_list: [l1]

  k_list: [10]

evaluation:
  val: false

output:
  pickle_filename: 'results/test1_result.pkl'